export const permissionCatalog = [
  { key: 'dashboard.view', module: 'dashboard', action: 'view', description: 'View dashboard summary' },
  { key: 'sales.view', module: 'sales', action: 'view', description: 'View sales records' },
  { key: 'sales.create', module: 'sales', action: 'create', description: 'Create sales' },
  { key: 'sales.edit', module: 'sales', action: 'edit', description: 'Edit sales' },
  { key: 'sales.delete', module: 'sales', action: 'delete', description: 'Delete sales' },
  { key: 'sales.discount', module: 'sales', action: 'discount', description: 'Apply sale discounts' },
  { key: 'refunds.create', module: 'refunds', action: 'create', description: 'Create refunds' },
  { key: 'products.view', module: 'products', action: 'view', description: 'View products' },
  { key: 'products.create', module: 'products', action: 'create', description: 'Create products' },
  { key: 'products.edit', module: 'products', action: 'edit', description: 'Edit products' },
  { key: 'products.delete', module: 'products', action: 'delete', description: 'Delete products' },
  { key: 'inventory.view', module: 'inventory', action: 'view', description: 'View stock and movements' },
  { key: 'inventory.adjust', module: 'inventory', action: 'adjust', description: 'Adjust stock levels' },
  { key: 'purchases.view', module: 'purchases', action: 'view', description: 'View purchases' },
  { key: 'purchases.create', module: 'purchases', action: 'create', description: 'Create purchases' },
  { key: 'purchases.edit', module: 'purchases', action: 'edit', description: 'Edit purchases' },
  { key: 'purchases.delete', module: 'purchases', action: 'delete', description: 'Delete purchases' },
  { key: 'expenses.view', module: 'expenses', action: 'view', description: 'View expenses' },
  { key: 'expenses.create', module: 'expenses', action: 'create', description: 'Create expenses' },
  { key: 'expenses.edit', module: 'expenses', action: 'edit', description: 'Edit expenses' },
  { key: 'expenses.delete', module: 'expenses', action: 'delete', description: 'Delete expenses' },
  { key: 'customers.view', module: 'customers', action: 'view', description: 'View customers' },
  { key: 'customers.edit', module: 'customers', action: 'edit', description: 'Manage customers' },
  { key: 'suppliers.view', module: 'suppliers', action: 'view', description: 'View suppliers' },
  { key: 'suppliers.edit', module: 'suppliers', action: 'edit', description: 'Manage suppliers' },
  { key: 'staff.view', module: 'staff', action: 'view', description: 'View staff records' },
  { key: 'staff.manage', module: 'staff', action: 'manage', description: 'Manage staff and logins' },
  { key: 'roles.view', module: 'roles', action: 'view', description: 'View roles and permissions' },
  { key: 'roles.manage', module: 'roles', action: 'manage', description: 'Manage roles and permissions' },
  { key: 'reports.view', module: 'reports', action: 'view', description: 'View reports' },
  { key: 'logs.view', module: 'logs', action: 'view', description: 'View activity logs' },
  { key: 'settings.view', module: 'settings', action: 'view', description: 'View settings' },
  { key: 'settings.manage', module: 'settings', action: 'manage', description: 'Manage settings' }
] as const;

export const defaultStaffPermissionKeys = [
  'dashboard.view',
  'sales.view',
  'sales.create',
  'sales.edit',
  'sales.discount',
  'refunds.create',
  'products.view',
  'inventory.view',
  'customers.view',
  'customers.edit',
  'purchases.view',
  'expenses.view',
  'suppliers.view'
] as const;
