import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { activityRouter } from '../modules/activity/activity.routes';
import { businessRouter } from '../modules/business/business.routes';
import { customersRouter } from '../modules/customers/customers.routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { damagedStocksRouter } from '../modules/damaged-stocks/damaged-stocks.routes';
import { expensesRouter } from '../modules/expenses/expenses.routes';
import { productsRouter } from '../modules/products/products.routes';
import { purchasesRouter } from '../modules/purchases/purchases.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { rolesRouter } from '../modules/roles/roles.routes';
import { salesRouter } from '../modules/sales/sales.routes';
import { settingsRouter } from '../modules/settings/settings.routes';
import { suppliersRouter } from '../modules/suppliers/suppliers.routes';
import { usersRouter } from '../modules/users/users.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/business', businessRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/damaged-stocks', damagedStocksRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/products', productsRouter);
apiRouter.use('/sales', salesRouter);
apiRouter.use('/purchases', purchasesRouter);
apiRouter.use('/expenses', expensesRouter);
apiRouter.use('/customers', customersRouter);
apiRouter.use('/suppliers', suppliersRouter);
apiRouter.use('/activity-logs', activityRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/reports', reportsRouter);
